### ISSUE TITLE
Where is the kernel?

### ISSUE THREAD

**Issue by enesdogan00** [ugtgl/msm8952-shamrock_eco#1]
I couldn't find the kernel. Where is it?

**Comment by ugtgl** [comment]
Kernel source was on dualboot Ubuntu partition that I have wiped it. And I have no source right now but I have flashable kernel image.
Kernel kaynağı dualboot Ubuntudaydı ve sildikten sonra kayboldu. Sadece flashlanabilen kernel image var onu da bu ay içinde paylaşırım. Olmazsa kerneli baştan düzenleyip kodlarını burada paylaşacağım. Buraya da zamanında yükleyemedim zira yüklemesi çok uzun sürüyor, hatta hiç yüklenmiyordu.

**Comment by enesdogan00** [comment]
It'd be brilliant if you'd uploud it here. Thanks.

Buraya yüklersen süper olur, teşekkürler.

**Comment by ugtgl** [comment]
Yüklendi.
